import productImage from "../../../../assets/images/product-image-1.webp"
export const featuredProductsData = [
    {
        id: 1,
        image: productImage,
        pCategory: "Phone",
        pName: "JPhone 13 High Quality Value Buy Best Cam...",
        ratings: 5.0,
        totalRatings: 50,
        price: "900.00",
        discount: 0,
    },
    {
        id: 2,
        image: productImage,
        pCategory: "Audio",
        pName: "WH-1000XM4 Wireless Headphones High Qu...",
        ratings: 2.5,
        totalRatings: 120,
        price: "59.00",
        discount: 50,
    },
    {
        id: 3,
        image: productImage,
        pCategory: "Laptop",
        pName: "S21 Laptop Ultra HD LED Screen Feature 2023 ...",
        ratings: 3.2,
        totalRatings: 100,
        price: "199.00",
        discount: 10,
    },
    {
        id: 4,
        image: productImage,
        pCategory: "Camera",
        pName: "Mini Polaroid Camera for Girls with Flash Li...",
        ratings: 4.5,
        totalRatings: 70,
        price: "79.00",
        discount: 0,
    },
    {
        id: 5,
        image: productImage,
        pCategory: "Television",
        pName: "AG OLED65CXPUA 4K Smart OLED TV New ...",
        ratings: 5.0,
        totalRatings: 50,
        price: "2799.00",
        discount: 0,
    },
    
    {
        id: 6,
        image: productImage,
        pCategory: "Television",
        pName: "AG OLED65CXPUA 4K Smart OLED TV New ...",
        ratings: 5.0,
        totalRatings: 50,
        price: "2799.00",
        discount: 0,
    },
    {
        id: 7,
        image: productImage,
        pCategory: "Television",
        pName: "AG OLED65CXPUA 4K Smart OLED TV New ...",
        ratings: 5.0,
        totalRatings: 50,
        price: "2799.00",
        discount: 0,
    },
]